"""add_performance_indexes

Revision ID: 7ed34e4a807a
Revises: e35c1b869d1d
Create Date: 2026-06-12 22:44:26.059916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ed34e4a807a'
down_revision: Union[str, Sequence[str], None] = 'e35c1b869d1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_enrolments_user_cohort_status', 'enrolments', ['user_id', 'cohort_id', 'status'], unique=False)
    op.create_index('ix_learning_path_enrolments_user_path', 'learning_path_enrolments', ['user_id', 'path_id'], unique=False)
    op.create_index('ix_messages_user_read', 'messages', ['user_id', 'is_read'], unique=False)
    op.create_index('ix_submissions_user_assessment', 'submissions', ['user_id', 'assessment_id'], unique=False)
    op.add_column('users', sa.Column('setup_token_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'setup_token_expiry')
    op.drop_index('ix_submissions_user_assessment', table_name='submissions')
    op.drop_index('ix_messages_user_read', table_name='messages')
    op.drop_index('ix_learning_path_enrolments_user_path', table_name='learning_path_enrolments')
    op.drop_index('ix_enrolments_user_cohort_status', table_name='enrolments')
    # ### end Alembic commands ###
